{% set name = "holoplot" %}
{% set version = "0.1.0" %}
{% set sha256 = "8f5cc1f1bc058c38ae8bcadace7b09cb1acb581599e9db87c21c3a2e92281d48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bokeh >=0.12.15
    - holoviews >=1.10.4
    - pandas

test:
  imports:
    - holoplot
  requires:
    - nose
    - parameterized
  commands:
    - nosetests holoplot

about:
  home: https://pyviz.github.io/holoplot/
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A high-level plotting API for the PyData ecosystem built on HoloViews.
  description: |
    HoloPlot provides a high-level plotting API built on HoloViews that provides
    a general and consistent API for plotting data in all the abovementioned
    formats. HoloPlot can integrate neatly with the individual libraries if an
    extension mechanism for the native plot APIs is offered, or it can be used
    as a standalone component.
  doc_url: https://pyviz.github.io/holoplot/
  dev_url: https://github.com/pyviz/holoplot

extra:
  recipe-maintainers:
    - CurtLH
    - philippjfr
    - jbednar
